// frequency (in hertz)
export const noteFrequencies = {
  C3: 130.81,
  "C#3": 138.59,
  D3: 146.83,
  "D#3": 155.56,
  E3: 164.81,
  F3: 174.61,
  "F#3": 185.0,
  G3: 196.0,
  "G#3": 207.65,
  A3: 220.0,
  "A#3": 233.08,
  B3: 246.94,
  C4: 261.63,
  "C#4": 277.18,
  D4: 293.66,
  "D#4": 311.13,
  E4: 329.63,
  F4: 349.23,
  "F#4": 369.99,
  G4: 392.0,
  "G#4": 415.3,
  A4: 440.0,
  "A#4": 466.16,
  B4: 493.88,
  C5: 523.25,
  "C#5": 554.37,
  D5: 587.33,
  "D#5": 622.25,
  E5: 659.25,
  F5: 698.46,
  "F#5": 739.99,
  G5: 783.99,
  "G#5": 830.61,
  A5: 880.0,
  "A#5": 932.33,
  B5: 987.77,
  C6: 1046.5,
};

// abc notation translator
export const abcMapper = {
  C3: "C,",
  "C#3": "^C,",
  D3: "D,",
  "D#3": "^D,",
  E3: "E,",
  F3: "F,",
  "F#3": "^F,",
  G3: "G,",
  "G#3": "^G,",
  A3: "A,",
  "A#3": "^A,",
  B3: "B,",
  C4: "C",
  "C#4": "^C",
  D4: "D",
  "D#4": "^D",
  E4: "E",
  F4: "F",
  "F#4": "^F",
  G4: "G",
  "G#4": "^G",
  A4: "A",
  "A#4": "^A",
  B4: "B",
  C5: "c",
  "C#5": "^c",
  D5: "d",
  "D#5": "^d",
  E5: "e",
  F5: "f",
  "F#5": "^f",
  G5: "g",
  "G#5": "^g",
  A5: "a",
  "A#5": "^a",
  B5: "b",
  C6: "c'",
};

// 16 bars progression logic (64 beats total)
export const chordProgressions = {
  "C Major": {
    // a massive pop journey: verse -> pre-chorus -> huge chorus -> resolution
    Pop: [
      "C",
      "G",
      "Am",
      "F",
      "C",
      "G",
      "F",
      "C",
      "Am",
      "F",
      "C",
      "G",
      "Dm",
      "F",
      "G",
      "C",
    ],
    // deep melancholy that shifts around before settling back into the minor key
    Melancholy: [
      "Am",
      "F",
      "C",
      "G",
      "Am",
      "Em",
      "F",
      "G",
      "Am",
      "F",
      "C",
      "G",
      "Dm",
      "Am",
      "Em",
      "Am",
    ],
    // a smooth, wandering R&B progression that ends on a classic turnaround
    "Jazz / R&B": [
      "Dm",
      "G",
      "C",
      "Am",
      "Dm",
      "G",
      "C",
      "Am",
      "F",
      "G",
      "Em",
      "Am",
      "Dm",
      "G",
      "C",
      "C",
    ],
  },
  "G Major": {
    Pop: [
      "G",
      "D",
      "Em",
      "C",
      "G",
      "D",
      "C",
      "G",
      "Em",
      "C",
      "G",
      "D",
      "Am",
      "C",
      "D",
      "G",
    ],
    Melancholy: [
      "Em",
      "C",
      "G",
      "D",
      "Em",
      "Bm",
      "C",
      "D",
      "Em",
      "C",
      "G",
      "D",
      "Am",
      "Em",
      "Bm",
      "Em",
    ],
    "Jazz / R&B": [
      "Am",
      "D",
      "G",
      "Em",
      "Am",
      "D",
      "G",
      "Em",
      "C",
      "D",
      "Bm",
      "Em",
      "Am",
      "D",
      "G",
      "G",
    ],
  },
};

// maps the active chord to its exact piano keys (tier 1: gold notes)
export const chordDictionary = {
  C: ["C", "E", "G"],
  G: ["G", "B", "D"],
  F: ["F", "A", "C"],
  Am: ["A", "C", "E"],
  Dm: ["D", "F", "A"],
  Em: ["E", "G", "B"],
  D: ["D", "F#", "A"],
  Bm: ["B", "D", "F#"],
};

// maps the selected key signature to its allowed scale notes (tier 2: silver notes)
export const keySignatures = {
  "C Major": ["C", "D", "E", "F", "G", "A", "B"],
  "G Major": ["G", "A", "B", "C", "D", "E", "F#"],
};

export const motifLibrary = {
  Pop: [
    {
      name: "steady",
      rhythm: "* * */2*/2 * | ",
      ending: "* * *2 | ",
    },
    {
      name: "bouncy",
      rhythm: "* z/2 */2 * * | ",
      ending: "* z/2 */2 *2 | ",
    },
    {
      name: "driving",
      rhythm: "*/2 z/2 */2*/2 * * | ",
      ending: "*/2 z/2 */2*/2 *2 | ",
    },
    {
      name: "active",
      rhythm: "* */2*/2 * */2*/2 | ",
      ending: "* */2*/2 *2 | ",
    },
  ],
  "Jazz / R&B": [
    {
      name: "laid back",
      rhythm: "* z * z | ",
      ending: "* z *2 | ",
    },
    {
      name: "swingy",
      rhythm: "z/2 */2 * z/2 */2 * | ",
      ending: "z/2 */2 * *2 | ",
    },
    {
      name: "syncopated",
      rhythm: "z * z/2 */2 * | ",
      ending: "z * *2 | ",
    },
    {
      name: "smooth",
      rhythm: "*/2*/2 z/2 */2 * * | ",
      ending: "*/2*/2 z/2 */2 *2 | ",
    },
  ],
  Melancholy: [
    {
      name: "long & slow",
      rhythm: "*2 * * | ",
      ending: "*2 *2 | ",
    },
    {
      name: "hesitant",
      rhythm: "*2 z/2 */2 * | ",
      ending: "*2 z z | ",
    },
    {
      name: "steady calm",
      rhythm: "* *2 * | ",
      ending: "* *2 z | ",
    },
    {
      name: "tender",
      rhythm: "z/2 */2 *2 * | ",
      ending: "z/2 */2 *2 z | ",
    },
  ],
};

export const tier1 = ["C", "E", "G"];
export const tier2 = ["D", "F", "A", "B"];
